spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.audio.transcription.base-url=https://api.groq.com/openai
spring.ai.openai.audio.transcription.options.model=whisper-large-v3
spring.ai.openai.audio.transcription.options.response-format=json
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB